"""Add x,y,width,height to Note

Revision ID: aa152c6b00a3
Revises: 8849638bb6b5
Create Date: 2025-09-02 22:22:11.715788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa152c6b00a3'
down_revision: Union[str, Sequence[str], None] = '8849638bb6b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('x', sa.Float(), nullable=True))
    op.add_column('notes', sa.Column('y', sa.Float(), nullable=True))
    op.add_column('notes', sa.Column('width', sa.Float(), nullable=True))
    op.add_column('notes', sa.Column('height', sa.Float(), nullable=True))
    op.drop_column('notes', 'archived')
    op.drop_column('notes', 'pinned')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('pinned', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('notes', sa.Column('archived', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('notes', 'height')
    op.drop_column('notes', 'width')
    op.drop_column('notes', 'y')
    op.drop_column('notes', 'x')
    # ### end Alembic commands ###
